site_name: NamedTensor
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
docs_dir: tree
extra_css: [doc.css]
site_url: http:///

markdown_extensions:
    - math
    - sane_lists
    - def_list

theme: readthedocs
